version: "3.8"

services:
  db:
    image: postgres
    container_name: brainly-postgres
    environment:
      POSTGRES_USER: brainuser
      POSTGRES_PASSWORD: brainpass
      POSTGRES_DB: brainlydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - brainly-net
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: brainly-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: anudeepavula
      DB_PASSWORD: anudeepavula
      DB_NAME: brainlydb
    depends_on:
      - db
    networks:
      - brainly-net

networks:
  brainly-net:

volumes:
  db_data:
